precious/blog/urls.py
from django.urls import path
from . import views 
from .feeds import LatestPostsFeed

urlpatterns = [
    #path('', views.PostList.as_view(), name='post_list'),
    path('',views.post_list, name='post_list'),
    path('post/<slug:slug>', views.post_detail, name='post_detail'),
    path('insert', views.CreateInsertionView.as_view(), name='insert'),
    path('hank', views.search_forms, name='search_forms'),
    path("feed/rss", LatestPostsFeed(), name="post_feed"),
    path('contact', views.ContactsView.as_view(), name = 'contact'),
    path('support', views.SupportView.as_view(), name = 'support'),
]

precious/precious/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from graphene_django.views import GraphQLView
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    "posts": PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path("graphql", GraphQLView.as_view(graphiql=True)),
    path('', include('blog.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] 


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

precious/blog/models/base.py
from django.db import models 


class Base(models.Model):
	STATUS = (
		('draft', 'در حال انتظار'),
		('published', 'منتشر شده'),
		)

	created = models.DateTimeField(auto_now_add = True, verbose_name='ساخت',null=True)

	updated = models.DateTimeField(auto_now = True,verbose_name='آپدیت')

	status = models.CharField(max_length=60, choices = STATUS, default='draft', verbose_name='وضعیت')
	
	class Meta:
		abstract = True

precious/blog/models/category.py
from django.db import models 
from multiselectfield import MultiSelectField
from .choices import *


class Category(models.Model): 
    cats = MultiSelectField(choices=CATS)

precious/blog/models/choices.py
LANGTAGS = (
    ('Python','Python'),
    ('Java','Java'),
    ('JavaScript','JavaScript'), 
    ('Php','Php'),
    ('Wordpress','Wordpress'),
    ('BootStrap','BootStrap'),
    ("Html & Css","Html & Css"),
    ('SQLite','SQLite'),
    ('MySQL','MySQL'),
    ('PostgreSQL','PostgreSQL'),
    ('C#','C#'),
    ('Git','Git'),
    ('Docker','Docker'),
    ('Sass','Sass'),
    ('Scss','Scss'),
    ('R','R'),
    ('Kotlin','Kotlin'),
    ('Go','Go'),
    ('C++','C++'),
    ('C','C'),
    ('JSON(API)','JSON(API)'),
    ('Ajax','Ajax'),
    ('AngularJS','AngularJS'),
    ("React","React"),
    ('JQuery','JQuery'),
    ('Vue','Vue'),
    ('Node.js','Node.js'),
    ('Raspberrypi','Raspberrypi'),
    ('ASP','ASP'),
    ('Django','Django'),
    ('Express.js','Express.js'),
    ('Flask','Flask'),
    ('CherryPy','CherryPy'),
    ('GraphQL','GraphQL'),
    ('TensorFlow','TensorFlow'),
    ('Pandas','Pandas'),
    ('Numpy','Numpy'),
    ('PyTorch','PyTorch'),
    ('Keras','Keras'),
    ('Theano','Theano'),
    ('MatPlotLib','MatPlotLib'),
    ('SciPy','SciPy'),
    ('PyGame','PyGame'),
    ('BS4','BS4'),
    ('Pillow','Pillow'),
    ('Meteor','Meteor'),
    ('Next.js','Next.js'),
    ('Ionic','Ionic'),
    ('Winjs','Winjs'),
    ('Selenium','Selenium'),
    ('OpenCV','OpenCV'),
    ("Dojo","Dojo"),
    ('Velocity.js','Velocity.js'),
    )

CATS = (
    ("Artificial Intelligence and Machine Learning","Artificial Intelligence and Machine Learning"),
    ("Security","Security"),
    ("Data Science/Analytics","Data Science/Analytics"),
    ("Software Development", "Software Development"),
    ("Computer Networking", "Computer Networking"),
    ("Frontend Development","Frontend Development"),
    ("Backend development", "Backend development"),
    ("Mobile Development", "Mobile Development"),
    ("Desktop Development", "Desktop Development"),
    ("DevOps Development","DevOps Development"),
    ("Game Development","Game Development"),
    ("Web Development","Web Development"),
    ("Cryptography Development","Cryptography Development"),
    ("CryptoCurrnecy Development","CryptoCurrnecy Development"),
    ("BlockChain Development","BlockChain Development"),
    ("Database Development",  "Database Development"),

)

precious/blog/models/comment.py
from django.db import models
from .post import Post 
from ckeditor_uploader.fields import RichTextUploadingField

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

precious/blog/models/insertion.py
from django.db import models
from .category import Category
from .langtag import LangTag

class Insertion(models.Model):
    project_link = models.URLField(verbose_name='لینک پروژه شما')
    
    your_email  = models.EmailField(verbose_name='ایمیل شما :)')

    cats = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='insertions')

    langtags = models.ForeignKey(LangTag, on_delete=models.CASCADE, related_name='insertions')

    

precious/blog/models/langtag.py
from django.db import models
from multiselectfield import MultiSelectField
from django.utils.translation import ugettext_lazy as _
from .choices import *



class LangTag(models.Model):
    langtags = MultiSelectField(choices=LANGTAGS)

precious/blog/models/post.py
# Create your models here.
from django.db import models
from multiselectfield import MultiSelectField
from .choices import *
from .base import Base
from .category import Category
from ckeditor_uploader.fields import RichTextUploadingField
from .langtag import LangTag
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
class Post(Base):
	title = models.CharField(max_length=25)

	slug = models.SlugField(max_length=200, unique=True)

	url = models.URLField(max_length=100)

	stars = models.IntegerField(default=0)

	content = RichTextUploadingField(blank=True)
	
	summary = models.CharField(max_length=300,blank=True,null=True,default='')

	cat = MultiSelectField(choices=CATS)

	video = models.URLField(max_length=1000)
	
	langtag  = MultiSelectField(choices=LANGTAGS)

	author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts")


		
	def __str__(self):
		return self.title
	
	class Meta:	
		ordering = ['-created']


'''
	def get_absolute_url(self):
		return reverse('blog:post_detail', (), {'id': self.id})
'''

precious/blog/forms.py
from django import forms
from .models import *
from ckeditor.widgets import CKEditorWidget
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.core.validators import RegexValidator,URLValidator, EmailValidator
from .models import choices
'''
class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(),required=True, max_length=100)
    content = RichTextField()

    class Meta:
        model  = Post
        fields = ('title','content',)
'''
class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget(config_name='comments'),required=True, max_length=2048)
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class PostAdminForm(forms.ModelForm):
    cats = forms.MultipleChoiceField(label="", choices=choices.CATS, widget=forms.CheckboxSelectMultiple())
    langtags = forms.MultipleChoiceField(label="", choices=choices.LANGTAGS, widget=forms.CheckboxSelectMultiple())
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['summary'].required = True
        self.fields['content'].required = True
        self.fields['title'].required = True
        self.fields['url'].required = True
    class Meta:
        model = Post
        fields = '__all__'

class InsertionAdminForm(forms.ModelForm):
    
    cats = forms.MultipleChoiceField(label="", choices=choices.CATS, widget=forms.CheckboxSelectMultiple())
    langtags = forms.MultipleChoiceField(label="", choices=choices.LANGTAGS, widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Insertion
        fields = '__all__'



class SearchForm(forms.Form):
    search = forms.CharField(required=False, label="")
    search.widget = forms.TextInput(attrs={'placeholder':"تایپ کنید: ",'name': 'email'})

class TableSearchForm(forms.Form):
    cats = forms.MultipleChoiceField(label="", choices=choices.CATS, widget=forms.CheckboxSelectMultiple())
    langtags = forms.MultipleChoiceField(label="", choices=choices.LANGTAGS, widget=forms.CheckboxSelectMultiple())
    stars = forms.IntegerField(label="ستاره ها")
    
class InsertionForm(forms.ModelForm):
    cats = forms.MultipleChoiceField(label="", choices=choices.CATS, widget=forms.CheckboxSelectMultiple())
    langtags = forms.MultipleChoiceField(label="", choices=choices.LANGTAGS, widget=forms.CheckboxSelectMultiple())
    your_email = forms.EmailField(label=_("ایمیل شما دوست عزیز "))
    project_link = forms.URLField(label = _('لینک پروژه شما ای دوست گل :'))
    class Meta:
        model = Insertion
        fields = '__all__'


    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(InsertionForm, self).__init__(*args, **kwargs)
        self.fields['project_link'].help_text = _('یک لینکی استفاده کن که به .git ختم شه گل !')
        self.fields['project_link'].label = _('لینک پروژه')
        self.fields['project_link'].validators.append(RegexValidator(
            regex=r'^\/([^/]+)\/([^/]+).git(/[^#]+)?(#(.*))?$',
            message='باید یک پروژه گیت باشه گل!',
        ))
        self.fields['project_link'].validators.append(URLValidator(schemes=['http', 'https']))
        self.fields['your_email'].validators.append(EmailValidator(message = _('please provide a valid email.')))

precious/blog/views.py
from django.shortcuts import render, reverse,get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q 
from django.utils.translation import gettext_lazy as _

from django.views import generic
# POSTGRESQL 
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

# Internal imports 
from .models import Post, Comment
from .filters import PostFilter
from .forms import CommentForm, SearchForm,TableSearchForm, InsertionForm

def post_list(request):
	## WITHOUT THE POSTGRESQL VECTOR SEARCH
	posts = Post.objects.filter(status='published').order_by('-created')
	if 'search' in request.GET:
		form = SearchForm(request.GET)
		if form.is_valid():
			cd = form.cleaned_data['search']
			search_result = posts.filter(Q(title__icontains = cd ) | Q(summary__icontains = cd ) |Q(content__icontains= cd ))

		else: 
			search_result = ' مقاله ای یافت نشد'
	else: 
		form = SearchForm(request.GET)
		search_result = ' مقاله ای یافت نشد'

	all_posts_count = posts.count()
	myFilter = PostFilter(request.GET, queryset=posts)
	filtered = myFilter.qs	
	# PAGINGATION
	paginator = Paginator(filtered, 3)  # 3 posts in each page
	page = request.GET.get('page')
	try:
		post_list = paginator.page(page)
	except PageNotAnInteger:
			# If page is not an integer deliver the first page
		post_list = paginator.page(1)
	except EmptyPage:
		# If page is out of range deliver last page of results
		post_list = paginator.page(paginator.num_pages)



	
	if request.method == 'POST':
		myform = TableSearchForm(request.POST)
		if myform.is_valid():
			cats = form.cleaned_data.get('cats')
			langtags = form.cleaned_data.get('langtags')
			stars = form.cleaned_data.get('stars')
			# do something with your results
			#table_search_results = posts.filter(Q(title__icontains = cd ) | Q(summary__icontains = cd ) |Q(content__icontains= cd ))
			print(stars)
			print(langtags)
			print(cats)
	else:
		myform = TableSearchForm

	

	context = {'all_posts_count':all_posts_count,'page': page,'myFilter':myFilter,'filtered':filtered, 'search_result':search_result,'form':form , 'myform':myform}
	return render(request, 'blog/post_list.html',context)


def post_detail(request, slug):
	template_name = 'blog/post_detail.html'
	post = get_object_or_404(Post, slug=slug)
	comments = post.comments.filter(active=True)
	new_comment = None
	# Comment posted
	if request.method == 'POST':
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():

			# Create Comment object but don't save to database yet
			new_comment = comment_form.save(commit=False)
			# Assign the current post to the comment
			new_comment.post = post
			# Save the comment to the database
			new_comment.save()
	else:
		comment_form = CommentForm()

	return render(request, template_name, {'post': post,
										   'comments': comments,
										   'new_comment': new_comment,
										   'comment_form': comment_form})

def search_forms(request):
	return render(request, 'blog/search_forms.html',{})

class CreateInsertionView(generic.CreateView):
	model  = Post
	form_class = InsertionForm
	template_name = 'blog/insertion_create.html'


class ContactsView(generic.TemplateView):
	template_name = 'blog/contacts.html'

class SupportView(generic.TemplateView):
	template_name = 'blog/support.html'

precious/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>Precious Source - {% block title %}      {% endblock %}</title>

	<!-- DJANGO STATIC FILES CONFIG -->

	<link href="{% static 'blog/css/style.css' %}" type="text/css" rel="stylesheet">
	<link href="{% static 'blog/css/fonts.css' %}" type="text/css" rel="stylesheet">
	<link href="{% static 'blog/css/navbar.css' %}" type="text/css"  rel="stylesheet">
	<link href="{% static 'blog/css/footer.css' %}" type="text/css" rel="stylesheet">
	<link href="{% static 'blog/lib/fontawesome-pro-5.15.3/css/all.min.css' %}" type="text/css" rel="stylesheet">

	<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

</head>
<body>
	<nav id="main-navbar">
		<ul>
			<li>
				<a href="#">خانه</a>
			</li>
			<li>
				<a href="#">داک</a>
			</li>
			<li>
				<a href="#">کانتریبیوت</a>
			</li>
			<li class="navbar-search">
				<form method="GET" action="#">
					<div class="navbar-search-button">
						<i class="far fa-search search-icon"></i>
						<i class="fal fa-times close-icon" style="display: none;"></i>
					</div>
					<div class="navbar-search-input">
						<input type="text" name="navbar-search" placeholder="تایپ کنید:">
					</div>
					<div class="navbar-search-submit">
						<button type="submit" disabled>
							<i class="far fa-search"></i>
						</button>
					</div>
				</form>
			</li>
			<li>
				<!-- <img src="#"> -->
				<a href="#">&lt;&#47;Logo&gt;</a>
			</li>
		</ul>
	</nav>
	<content>
	<!-- DJANGO BASE PAGE (All other contents will be imported here)-->
	
		  {% block content %}

			{% endblock %}

	</content>
	<footer>
		<div class="footer-contactInfo">
			<ul>
				<li>
					ما؟
				</li>
				<li>
					<i class="fas fa-envelope"></i>
					<a href="emailto:">ایمیل: precious-source@gmail.com</a>
				</li>
				<li>
					<i class="fab fa-github"></i>
					<a href="https://github.com/khoramism/precious-source">گیت هاب: khoramism/precious-source</a>
				</li>
			</ul>
		</div>
		<div class="footer-links">
			<ul>
				<li>
					لینک&zwnj;های باحال
				</li>
				<li>
					<a href="#">گوگل</a>
				</li>
				<li>
					<a href="#">لینوکس</a>
				</li>
			</ul>
		</div>
		<div class="footer-links">
			<ul>
				<li>
					صفحه&zwnj;های باحال
				</li>
				<li>
					<a href="https://www.github.com/khoramism/precious-source/HelpAPI.md">API</a>
				</li>
				<li>
					<a href="https://www.github.com/khoramism/precious-source/contribute.md">بهبود دادن پرشس سورس</a>
				</li>
			</ul>
		</div>
		
	</footer>
	<script type="text/javascript" src="{% static 'blog/js/navbar.js' %}"></script>
</body>
</html>

precious/blog/templates/blog/card.html
<head>
	<link href="{% static 'blog/css/post_card.css' %}" type="text/css" rel="stylesheet">
</head>

<div class="posts-container">
  <div class="post-card">
    <div class="post-img">
      <img src="{% static 'blog/img/code.jpg' %}">
    </div>
    <div class="post-info">
      <div class="post-title">
        <p>{{ post.title }}</p>
      </div>
      <div class="post-metadata">
        <div class="post-whoWhen">
          <p>توسط <a href="#" class="post-author">{{ post.author }}</a> در <span class="post-date">{{ post.created_on}}</span></p>
        </div>
        <div class="post-rating">
          <!--
            Full star  => fas fa-star
            Half star  => fa-star-half-alt
            Empty star => far fa-star
            -->
          <p><i class="fas fa-star"></i> <span>{{ post.stars }}</span></p>
        </div>
      </div>
      <div class="post-summary">
        {{ post.media }}
        {{post.content |safe }}
      </div>
      <div class="post-tags">
        <div><a href="#">تگ</a>{{ post.cats }}</div>
        {% for category in post.cat %}
        <br>
        <br>
        {{category}}
        {% endfor %}
        <br>
        {% for tag in post.langtag %}
        <br>
        <br>
        {{tag}}
        {% endfor %}
      </div>
    </div>
  </div>
</div>

precious/blog/templates/blog/contacts.html
{% extends 'blog/base.html' %}

{% block content %}




{% endblock %}

precious/blog/templates/blog/insertion_create.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<head>
    <meta charset="UTF-8">
    <title>{{ indexFunc.title }}</title>

    <link href="{% static 'blog/css/form.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'blog/css/dropdown.css' %}" type="text/css" rel="stylesheet">    
</head>

<div class="form-container">
  <form method="post" action="#">
    {% csrf_token %}
    <div class="form-section-container">
      <div class="form-label-div">
        <label for="id_your_email">ایمیل شما</label>
      </div>
      <div class="form-input filled en">
        {{ form.your_email }}
        <script type="text/javascript">
          document.getElementById("id_your_email").setAttribute("placeholder", "Enter your email:")
        </script>
      </div>
    </div>
    <div class="form-section-container">
      <div class="form-label-div">
        <label for="id_your_email">لینک پروژه شما</label>
      </div>
      <div class="form-input filled en">
        {{form.project_link }}
        <script type="text/javascript">
          document.getElementById("id_project_link").setAttribute("placeholder", "Enter the project's URL:")
        </script>
      </div>
    </div>
    <div class="form-section-container tag-search">
      <div class="form-label-div">
        <label for="tag-search-input__langtags">چه تکنولوژی&zwnj;هایی در پروژه&zwnj;ی شما به کار رفته؟</label>
      </div>
      <div class="dropdown-container">
        <div class="dropdown">
          <div class="dropdown-header">
            <input id="tag-search-input__langtags" type="text" name="tag-search__langtags" placeholder="تایپ کنید:">
            <i class="fas fa-sort-down"></i>
          </div>
          <div id="dropdown__langtags" class="dropdown-options-container en">
            {{ form.langtags }}
            <p class="dropdown-noresult">نتیجه&zwnj;ای یافت نشد.</p>
          </div>
        </div>
      </div>
      <div id="selected-tags-container__langtags" class="selected-tags-container"></div>
    </div>
    <div class="form-section-container tag-search">
      <div class="form-label-div">
        <label for="tag-search-input__cats">پروژه&zwnj;ی شما در چه دسته&zwnj;بندی&zwnj;هایی قرار می&zwnj;گیرد؟</label>
      </div>
      <div class="dropdown-container">
        <div class="dropdown">
          <div class="dropdown-header">
            <input id="tag-search-input__cats" type="text" name="tag-search__cats" placeholder="تایپ کنید:">
            <i class="fas fa-sort-down"></i>
          </div>
          <div id="dropdown__cats" class="dropdown-options-container en">
            {{ form.cats }}
            <p class="dropdown-noresult">نتیجه&zwnj;ای یافت نشد.</p>
          </div>
        </div>
      </div>
      <div id="selected-tags-container__cats" class="selected-tags-container"></div>
    </div>
    <div class="form-section-container submit">
      <button type="submit">تایید</button>
    </div>
  </form>
</div>

<script type="text/javascript" src="{% static 'blog/js/dropdown.js' %}"></script>

{% endblock %}

precious/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
  <head>
    <meta charset="UTF-8">
    <title>{{ indexFunc.title }}</title>

    <link href="{% static 'blog/css/post_detail.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'blog/css/form.css' %}" type="text/css" rel="stylesheet">

    <link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.4.1/styles/monokai-sublime.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.4.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
  </head>


<header class="post-headear">
  <div class="post-title">
    <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
  </div>
  <div class="post-meta">
    <p class="post-whoWhen">توسط <span>{{ post.author }}</span> در <span>{{ post.created_on }}</span></p>
    <p class="post-stars"><i class="fas fa-star"></i> <span>{{ post.stars }}</span></p>
  </div>
  <div class="post-tags en">
    <div id="post-tags-row__langtag" class="post-tags-row">
      {% for tag in post.langtag %}
        <div><p>{{ tag }}</p></div>
      {% endfor %}
    </div>
    <div id="post-tags-row__cat" class="post-tags-row">
      {% for category in post.cat %}
        <div><p>{{ category }}</p></div>
      {% endfor %}
    </div>
  </div>
</header>
<main class="post-main">
  <aside class="post-toolbar">
    <div class="post-toolbar-item">
      <a href="#"><i class="fas fa-share"></i>اشتراک گذاری</a>
    </div>
    <div class="post-toolbar-item">
      <a href="#"><i class="fab fa-github"></i>گیت هاب</a>
    </div>
    <div class="post-toolbar-item">
      <a href="#"><i class="fas fa-download"></i>دانلود</a>
    </div>
    <div class="post-toolbar-item">
      <a href="#post-write-comment"><i class="fas fa-comment"></i>کامنت</a>
    </div>
  </aside>
  <article class="post-article en">
    {{ post.media }}
    {{post.content |safe }}
  </article>
</main>

<div class="form-container">
  <form id="post-write-comment" method="post">
    {{ comment_form | crispy }}
    {% csrf_token %}
    <div class="form-section-container submit">
      <button type="submit" class="">ارسال</button>
    </div>
    <script type="text/javascript">
      $("#post-write-comment .form-group").addClass("form-section-container");
      $("#post-write-comment .form-group > div").addClass("form-input filled");
      $("#post-write-comment #id_name").attr("placeholder", "نام شما در قسمت کامنت ها:");
      $("#post-write-comment #id_email").attr("placeholder", "ایمیل خود را وارد کنید:");
      $("#post-write-comment #id_body").attr("placeholder", "نظر خود را بنویسید:");
    </script>
  </form>
</div>

<div id="post-comment-section">
  <h2 id="post-comment-section__count">تا الان {{ comments.count }} تا نظر داده شده.</h2>
  {% for comment in comments %}
  <div class="comments">
    <p class="comment-metadata">
      <span class="comment-metadata__name">{{ comment.name }}</span>
      در تاریخ
      <span class="comment-metadata__date">{{ comment.created_on }}</span>
      گفته:
    </p>
    {{ comment.body | linebreaks }}
  </div>
  {% endfor %}
</div>
{% endblock %}

precious/blog/templates/blog/search_forms.html
{% extends 'blog/base.html' %}
{% block content %}
{% load static %}

{% endblock %}

precious/blog/templates/blog/support.html
{% extends 'blog/base.html' %}

{% block content %}




{% endblock %}}